### ISSUE TITLE
pip install ExecTrace from git (or from a PyPI package)

### ISSUE THREAD

**Issue by felipesanches** [felipesanches/AnotherWorld_VMTools#3]
https://github.com/felipesanches/ExecTrace

... instead of keeping our own copy of it in this repo.

**Comment by felipesanches** [comment]
This should go into the `requirements.txt` file

**Comment by toymak3r** [comment]
This could be done as git submodule from git, too.
Which do you prefer ?

**Comment by felipesanches** [comment]
I prefer requirements.txt

But leave this one to me. I noticed that the development of ExecTrace diverged between the upstream repo and the copy we have hosted here. So I want to ensure the newer ExecTrace does not introduce bugs. I will inspect this carefully before implementing the fix.

**Comment by felipesanches** [comment]
I need to fix #1 before, though

**Comment by felipesanches** [comment]
This was finally done this month ;-)
