### ISSUE TITLE
Review README.md usage instructions

### ISSUE THREAD

**Issue by felipesanches** [felipesanches/AnotherWorld_VMTools#7]
At https://github.com/felipesanches/AnotherWorld_VMTools/pull/6/commits/71a9b7c2ab9a060532b93b584d8e12d8d459de78 I have added detailed usage instructions.

@toymak3r, can you review that and let me know if it is easy to understand (and also if it is correct), please?

Feel free to suggest improvements and/or fixes.

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/AnotherWorld_VMTools/pull/8/commits/3c82dc370c66de83ff09a166356fe47d4e23c033 I made a few more changes to `README.md`

**Comment by toymak3r** [comment]
for sure.
Starting right now.

**Comment by toymak3r** [comment]
Done, I did additional details about development aspects of this tool.

**Comment by felipesanches** [comment]
thanks!
